#!/usr/bin/env python3
import argparse
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

parser = argparse.ArgumentParser()
parser.add_argument("--dev", action="store_true", help="Install dev requirements")
args = parser.parse_args()

# Create virtual environment
builder = venv.EnvBuilder(with_pip=True)
context = builder.ensure_directories(_VENV_DIR)
builder.create(_VENV_DIR)

# Upgrade dependencies
pip = [context.env_exe, "-m", "pip"]
subprocess.check_call(pip + ["install", "--upgrade", "pip"])
subprocess.check_call(pip + ["install", "--upgrade", "setuptools", "wheel"])

# Install requirements
# subprocess.check_call(pip + ["wheel", "https://www.piwheels.org/simple/numpy/numpy-2.0.2-cp39-cp39-linux_armv7l.whl#sha256=27740e75344b7522f6be4c3d694775369524f12e3b31327a3642a35f5b416db8"])
subprocess.check_call(
    pip
    + [
        "install",
        "-f",
        "https://synesthesiam.github.io/prebuilt-apps/",
        "--extra-index-url",
        "https://www.piwheels.org/simple",
        "-r",
        str(_PROGRAM_DIR / "requirements.txt"),
    ]
)

if args.dev:
    # Install dev requirements
    subprocess.check_call(
        pip + ["install", "-r", str(_PROGRAM_DIR / "requirements_dev.txt")]
    )
